name: 'Version to File'
description: 'Fetches the latest release tag and writes it into a file'
inputs:
  filename:
    description: 'The filename to write the version tag to'
    required: true
    default: '.VERSION'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filename }}
branding:
  icon: 'file-text'
  color: 'green'
